### ISSUE TITLE
Unknown error in the past 24 hours

### ISSUE THREAD

**Issue by alexanderfitu** [hacf-fr/hassRenaultZE#125] opened 2021-02-04 05:27 UTC
In the past 24 hours, it seems Renault have changed something on their end. My integration gives the following error:

`Logger: homeassistant.config_entries
Source: custom_components/renault/renault_hub.py:59
First occurred: 5:19:30 (1 occurrences)
Last logged: 5:19:30

Error setting up entry 5fde8781-e99b-4fe4-be5d-2ded5e226568 for renault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renault/__init__.py", line 34, in async_setup_entry
    await renault_hub.async_initialise(config_entry)
  File "/config/custom_components/renault/renault_hub.py", line 59, in async_initialise
    vehicles = await self._account.get_vehicles()
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_account.py", line 62, in get_vehicles
    return await self.session.get_account_vehicles(
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_session.py", line 172, in get_account_vehicles
    return await kamereon.get_account_vehicles(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 139, in get_account_vehicles
    await request(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 92, in request
    kamereon_response: models.KamereonResponse = schema.loads(response_text)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 761, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/usr/local/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 577, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 727, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'vehicleLinks': ['Missing data for required field.']}`

I deleted the integration and when I re installed, I was unable to login, with it giving me "unknown error"

**Comment by epenet** [comment] 2021-02-04 07:09
Duplicate of #120, changes on Renault servers

Please try https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.6

**Closed** 2021-02-04 07:49 UTC
Labels: duplicate
