### ISSUE TITLE
Sensors unavailable after some time and "failed to forward" errors

### ISSUE THREAD

**Issue by doppiaemme** [hacf-fr/hassRenaultZE#144] opened 2021-04-16 15:51 UTC
## Version of the custom_component
3.0.8

## Configuration

configured via UI

## Describe the bug
It worked for a few days, but after, all the sensors show "unavailable" status. 
After restarting HASS I still get several sensors unavailable.

![image](https://user-images.githubusercontent.com/3978350/115050760-60dcaa00-9edc-11eb-8476-717466da4f3e.png)

## Debug log

2021-04-16 16:17:19 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000663241597 cockpit data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.')
2021-04-16 16:17:19 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000663241597 battery data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.')
2021-04-16 16:17:19 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000663241597 charge_mode data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.')
2021-04-16 16:17:20 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000663241597 location data: Error communicating with API: ('err.tech.wired.kamereon-proxy', 'Failed to forward request to remote service.')
2021-04-16 16:17:20 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform renault
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
original_icon=entity.icon,
File "/config/custom_components/renault/sensor.py", line 108, in icon
charging = self.data.get_charging_status() == ChargeState.CHARGE_IN_PROGRESS
AttributeError: 'NoneType' object has no attribute 'get_charging_status'
2021-04-16 16:17:20 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up renault platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 213, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
original_icon=entity.icon,
File "/config/custom_components/renault/sensor.py", line 108, in icon
charging = self.data.get_charging_status() == ChargeState.CHARGE_IN_PROGRESS
AttributeError: 'NoneType' object has no attribute 'get_charging_status'

**Comment by epenet** [comment] 2021-04-16 16:11
Lots of error on the Renault server at the moment.
You can check the Renault app at the same time as the errors - it probably also fails.

**Comment by TheArcturian** [comment] 2021-04-19 20:02
Hmm, I have the same problem, but the Renault app works fine. Hopefully it will be solved soon.

**Comment by doppiaemme** [comment] 2021-04-20 10:23
The app always works fine, while the component shows random behaviours. 
It didn't work for 5 days and they it started working again. Not sure what goes on but the app seems to either have priority or a different access, as it never has glitches.

**Comment by TheArcturian** [comment] 2021-04-20 10:46
After restarting HA now, the sensors started to work again.
I have restarted HA multiple times the last days before today so something has probably been corrected recently.

**Comment by epenet** [comment] 2021-05-03 08:15
Hi @doppiaemme 
I have reviewed the issue, and I think that I found the root cause of your issues. In theory:
- `'Failed to forward request to remote service.'` is generated by Renault servers and there is nothing that we can do about it.
- The sensors should be created anyway (in `unavailable` status)
- When the Renault servers are available again, then they should become available and report the correct value

However, the `self.data.get_charging_status()`  error that happens due to the Renaul server failure is causing the sensors to not be created correctly, so even when the Renault servers are available again they do not come back online.

The issue should be fixed with PR #146

**Comment by doppiaemme** [comment] 2021-05-03 08:41
Hi @epenet 
I'm glad you found this!
not sure if possible or if it's a string value, but maybe rather than "unavailable" a better state could be "cloud unavailable" or similar, as it would clarify better it's the renault server having issues and not the local plugin?

**Comment by epenet** [comment] 2021-05-03 08:51
`Error communicating with API` is a clean error handled by the local plugin
`Error adding entities` and `Error while setting up` are "dirty" errors handled by HA because the local plugin didn't handle it

Because Renault have not made the API public, it's quite difficult to know what to expect from the Renault servers and we get new errors that nobody has seen before from time to time.

**Closed** 2021-07-15 08:36 UTC
