### ISSUE TITLE
Integration is gone after restart

### ISSUE THREAD

**Issue by jebeke65** [hacf-fr/hassRenaultZE#147] opened 2021-05-12 09:01 UTC
## Version of the custom_component
v3.0.8

## Configuration
Not applicable

## Describe the bug
Each time I restart home assistant, the integration is gone.
I need to re-add it.

There is - to me - no possibility to log, as the integration is gone each time I restart.
Can the integration be added manually in a yaml file ?

## Debug log

```text

Add your logs here.

```

**Comment by epenet** [comment] 2021-05-12 09:29
There is no plan to add YAML configuration.

You have not documented your setup atall, not did you describe how you have added the integration: did you use HACS or did you install it manually?

It sounds to me like the issue is related to your general HA setup and not directly related to the custom component.

**Comment by jebeke65** [comment] 2021-05-12 09:34
sorry about this :(
I have added the Renault integration using HACS.
I see the integration in the list of integrations 
![image](https://user-images.githubusercontent.com/47870698/117952719-b78ba700-b315-11eb-8e0e-c8568eb18c61.png)
I enter my credentials and the integration is added successfully.
I have the 1 device and 12 entities.
The Renault integration remains active until I restart home assistant, then it's not in the configuration-integrations board anymore and I have to re-add it

**Comment by epenet** [comment] 2021-05-12 09:42
Logging is added in the YAML so you should be able to do that regardless of the Renault misbehaviour.

**Comment by jebeke65** [comment] 2021-05-12 11:57
I took the time in the mean while to get rid of some warning/errors of other hacs components (e.g. version number, etc...) and now the problem does not occur anymore.
Strange :(

**Comment by epenet** [comment] 2021-05-12 13:03
It seems you can close the issue now...

**Closed** 2021-05-12 19:53 UTC
