### ISSUE TITLE
Error fetching hvac_status data

### ISSUE THREAD

**Issue by eviollet** [hacf-fr/hassRenaultZE#104] opened 2021-01-03 17:42 UTC
## Version of the custom_component
3.03

## Configuration

```yaml

2021-01-03 18:37:15 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000466599571 hvac_status data: This endpoint has been disabled: ('err.func.403', 'Operation not supported Operation not supported for this can (C1A)')

```

## Describe the bug
On startup, it seems that the hvac status and configuration information are not available and fail.
I can't find anything in the documentation stating that it shouldn't work. So, should this work?

## Debug log
Here is an extract of the log : 

2021-01-03 18:37:14 DEBUG (MainThread) [custom_components.renault.renault_vehicle] Finished fetching VF1AG000466599571 cockpit data in 0.372 seconds
2021-01-03 18:37:15 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 403 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/8244b99e-5ec1-4eb7-8695-2e0de0a7d427/kamereon/kca/car-adapter/v1/cars/VF1AG000466599571/hvac-status?country=FR: {"type":"FUNCTIONAL","messages":[{"code":"err.func.403","message":"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation not supported\",\"detail\":\"Operation not supported for this can (C1A)\"}]}"}],"errors":[{"errorCode":"err.func.403","errorMessage":"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation not supported\",\"detail\":\"Operation not supported for this can (C1A)\"}]}"}],"error_reference":"FUNCTIONAL"}
2021-01-03 18:37:15 ERROR (MainThread) [custom_components.renault.renault_vehicle] Error fetching VF1AG000466599571 hvac_status data: This endpoint has been disabled: ('err.func.403', 'Operation not supported Operation not supported for this can (C1A)')

I'm willing to give more data, but it seems that the rest of the log contains some quite sensitive information.

Hope this helps.
```

**Comment by epenet** [comment] 2021-01-04 08:33
@eviollet this is a duplicate of #51
Please review the comments there - I am open to all input for the best way to handle it...

**Closed by epenet** 2021-01-04 08:33 UTC
Labels: duplicate
