### ISSUE TITLE
 403 Client Error getting vehicles

### ISSUE THREAD

**Issue by cris88** [hacf-fr/hassRenaultZE#124] opened 2021-02-03 09:08 UTC
Anyone with the same problem?

2021-02-03 09:04:00 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ddb20384-ce31-4bce-a9f9-af6d2186a990 for renault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renault/__init__.py", line 27, in async_setup_entry
    await pyzeproxy.initialise(config_entry.data)
  File "/config/custom_components/renault/pyzeproxy.py", line 73, in initialise
    vehicles = await self._hass.async_add_executor_job(self._kamereon.get_vehicles)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyze/api/credentials.py", line 29, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyze/api/kamereon.py", line 123, in get_vehicles
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/vehicles?country=GB

**Comment by epenet** [comment] 2021-02-03 09:10
Duplicate of #120, changes on Renault servers

Please try https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.6

**Comment by cris88** [comment] 2021-02-03 11:13
thanks @epenet

**Closed** 2021-02-03 12:54 UTC
Labels: duplicate
