### ISSUE TITLE
Cannot find function to start the AC 

### ISSUE THREAD

**Issue by marciej123** [hacf-fr/hassRenaultZE#93] opened 2020-12-11 15:32 UTC
Hello,

I was wondering if you can add the function to start the AC?
The My-Renault app has this function and I believe it is also possible with the API: https://github.com/epenet/Renault-Zoe-API

Thanks

**Comment by epenet** [comment] 2020-12-11 15:35
That API was retired by Renault!
The new one is available on https://github.com/hacf-fr/renault-api/

Regarding the HVAC, it is already implemented in both the new API and this custom component.
What issues are you having with it?

**Comment by epenet** [comment] 2020-12-16 10:28
@marciej123 did you find it?

**Comment by epenet** [comment] 2020-12-17 13:31
Maybe duplicate of #51?

**Closed** 2020-12-17 19:52 UTC
Labels: question
