### ISSUE TITLE
Fixed: Missing data for required field / 403 Forbidden since 1st February

### ISSUE THREAD

**Issue by deephack1982** [hacf-fr/hassRenaultZE#120] opened 2021-02-01 10:58 UTC
Hello,

After entering my login details for Renault into the UI I get this error in the log and the message "unknown error occurred" in the Set Renault credentials window.

I'm on Home Assistant 2021.1.5

`Logger: aiohttp.server
Source: custom_components/renault/renault_hub.py:76
First occurred: 11:50:12 (2 occurrences)
Last logged: 11:52:53

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/renault/config_flow.py", line 50, in async_step_user
    return await self.async_step_kamereon()
  File "/config/custom_components/renault/config_flow.py", line 80, in async_step_kamereon
    accounts = await self.renault_hub.get_account_ids()
  File "/config/custom_components/renault/renault_hub.py", line 76, in get_account_ids
    for account in await self._client.get_api_accounts():
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_client.py", line 58, in get_api_accounts
    response = await self.get_person()
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_client.py", line 54, in get_person
    return await self.session.get_person()
  File "/usr/local/lib/python3.8/site-packages/renault_api/renault_session.py", line 175, in get_person
    return await kamereon.get_person(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 163, in get_person
    await request(
  File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 141, in request
    kamereon_response: models.KamereonResponse = schema.loads(response_text)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 761, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/usr/local/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 577, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 727, in load
    return self._do_load(
  File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'accounts': ['Missing data for required field.']}`

**Comment by epenet** [comment] 2021-02-01 11:08
Are you able to control your Renault vehicle correctly using MyRenault application?
Are you using the same credentials as MyRenault application (please note that the credentials from the Renault website are different from the credentials from MyRenault application)

Could you please also enable logging and provide logs so that we can improve the error message?
```yaml
logger:
  default: error
  logs:
    renault_api: debug
    custom_components.renault: debug
```

**Comment by deephack1982** [comment] 2021-02-01 11:52
Thanks for the quick reply. I can confirm that it's the correct login details and my app is working normally right now.

I've added the logger lines you posted to my configuration.yaml and restarted home assistant but adding the integration creates the same log that I posted before with no more details. Am I perhaps doing something wrong.

**Comment by deephack1982** [comment] 2021-02-01 11:57
Note that I can log in with the same details here https://myr.renault.se/

I can see my car and everything looks normal so I'm not sure why I'm getting a 403 error in Home Assistant.

**Comment by theneedyguy** [comment] 2021-02-01 12:03
I also have the same issue.
Integration version 3.0.6
Home Assistant Core: 2021.1.5

```text
2021-02-01 12:57:54 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 403 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxxxxxxxx/vehicles?country=CH: {"error":"access_denied","error_description":"Unauthorized"}
2021-02-01 12:57:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxxxxxx for renault
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/renault/__init__.py", line 34, in async_setup_entry
await renault_hub.async_initialise(config_entry)
File "/config/custom_components/renault/renault_hub.py", line 59, in async_initialise
vehicles = await self._account.get_vehicles()
File "/usr/local/lib/python3.8/site-packages/renault_api/renault_account.py", line 62, in get_vehicles
return await self.session.get_account_vehicles(
File "/usr/local/lib/python3.8/site-packages/renault_api/renault_session.py", line 188, in get_account_vehicles
return await kamereon.get_account_vehicles(
File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 224, in get_account_vehicles
await request(
File "/usr/local/lib/python3.8/site-packages/renault_api/kamereon/__init__.py", line 141, in request
kamereon_response: models.KamereonResponse = schema.loads(response_text)
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 761, in loads
return self.load(data, many=many, partial=partial, unknown=unknown)
File "/usr/local/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 577, in load
all_loaded = super().load(data, many=many, **kwargs)
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 727, in load
return self._do_load(
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
raise exc
marshmallow.exceptions.ValidationError: {'vehicleLinks': ['Missing data for required field.']}
```

**Comment by epenet** [comment] 2021-02-01 12:44
:( it looks like something changed on the Renault API servers.
This would be better discussed on https://github.com/hacf-fr/renault-api/

**Comment by theneedyguy** [comment] 2021-02-01 13:08
I just tried installing the Mobile App on another Android smartphone. I tried to login but it just says that there is a server errror. Might be temporary or something changed in the backend.

**Comment by epenet** [comment] 2021-02-01 13:39
I found the root cause for the two `marshmallow.exceptions.ValidationError` issues:
* `marshmallow.exceptions.ValidationError: {'vehicleLinks': ['Missing data for required field.']}`
* `marshmallow.exceptions.ValidationError: {'accounts': ['Missing data for required field.']}`
They should instead say "403 - Forbidden", and it will be fixed with PR https://github.com/hacf-fr/renault-api/pull/177 in the next release of renault-api

However, the underlying issue is still a problem on the Renault servers. Like @theneedyguy saysit might be temporary or something changed in the backend. The fact that installing the Mobile App on another Android smartphone fails tends to indicate a temporary bug on the Renault servers.

**Comment by epenet** [comment] 2021-02-01 14:52
I have just published an update on renault-api for the `Missing data for required field` issue.
Although it doesn't fix the underlying `Forbidden` issue it should at least report correctly.

This can be easily tested by adjusting the version number in the manifest.json file.
Can you please both try it and confirm?

**Comment by JeedHome44** [comment] 2021-02-01 20:46
So there is no solution at the moment?

**Comment by epenet** [comment] 2021-02-01 20:47
I have just released [v3.0.6](https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.6), which incorporates the fix from [renault-api](https://github.com/hacf-fr/renault-api/pull/182)

**Comment by epenet** [comment] 2021-02-01 20:53
@deephack1982 / @theneedyguy it's working ok for you?

**Comment by JeedHome44** [comment] 2021-02-01 21:14
we have just to update to 3.0.6? i'll test it

**Comment by epenet** [comment] 2021-02-01 21:18
I tested it on my personal setup and it worked correctly.

**Comment by JeedHome44** [comment] 2021-02-01 21:21
Ok for me too! Good job!

**Comment by epenet** [comment] 2021-02-04 07:52
I have reopened, and pinned this issue as I keep getting more requests!

**Comment by epenet** [comment] 2021-03-15 20:05
One month on I think it is time to close this issue.

**Closed by epenet** 2021-03-15 20:05 UTC

**Comment by sajikur** [comment] 2022-03-17 08:04
Unknown error occurred, again :(

Error occurred after new installation of integration renault. Old installation didn't update
Any ideas?

**Comment by epenet** [comment] 2022-03-17 08:11
This custom component has been deprecated since 2021.10 and should no longer be used.
It is now part of Home Assistant core, and should be removed from your custom components.

**Comment by epenet** [comment] 2022-03-17 08:16
See https://github.com/home-assistant/core/issues/68251 and https://github.com/home-assistant/core/pull/68260

**Comment by sajikur** [comment] 2022-03-17 08:57
> This custom component has been deprecated since 2021.10 and should no longer be used. It is now part of Home Assistant core, and should be removed from your custom components.

Thank you for your answer. I've not custom component about renault. I'm trying to reinstall integration but I see that error. Any ideas? Thx

**Comment by epenet** [comment] 2022-03-17 08:59
No more support here - please use issue tracker on Home Assistant Core now: https://github.com/home-assistant/core/issues/68251
