### ISSUE TITLE
Loss of adsl connection

### ISSUE THREAD

**Issue by JeedHome44** [hacf-fr/hassRenaultZE#41] opened 2020-07-28 17:40 UTC
Hello,

If I have an ADSL disconnection, Pyze no longer updates the information as soon as the ADSL has returned. The actions don't work too. I have to do a Hassio reboot for this to work.
Would there be a possible refresh solution through automation?

Thank you

**Comment by epenet** [comment] 2020-10-02 08:42
Hi @JeedHome44 ,

Can you update to [v3.0.0](https://github.com/epenet/hassRenaultZE/releases/tag/v3.0.0) and see if that is still an issue?

**Comment by JeedHome44** [comment] 2020-10-02 09:10
Hi,

My lan is Now with OpenMPTCPRouteur.
So, I have always connection.

I will try this 3.0 as soon as possible. 😉

**Comment by JeedHome44** [comment] 2020-10-06 20:57
Hi,
what does this version 3.0 bring?

**Comment by epenet** [comment] 2020-10-07 14:28
Mainly, it is configured through the UI
Secondly, all the results are full sensors now and there is no need to use attributes

**Comment by JeedHome44** [comment] 2020-10-07 16:02
I've never needed to use attributes personally.  I send all the information by HTTP request to Jeedom.  and it is Jeedom who activates each action by a script on Home Assistant 😄

**Comment by epenet** [comment] 2020-10-15 12:23
Can we close this issue then?

**Comment by JeedHome44** [comment] 2020-10-15 12:26
I didn't update because I don't understand what all these changes are all about.  it allows to continue to work even if the connection is lost?

**Comment by epenet** [comment] 2020-10-15 12:31
Your original issue doesn't have enough information to make an investigation.

If you wish to investigate it more, then you need to upgrade and try to replicate your issue.
If you do not wish to investigate it more, then just close this issue.

**Comment by epenet** [comment] 2020-10-24 16:50
I think I managed to replicate this... it occurs if the internet is not available during startup.
We should try to add a retry if it fails during startup.

**Comment by JeedHome44** [comment] 2020-10-24 17:36
Hello,

that would be great if you can add a new attempt if the first one fails!  😉

**Comment by epenet** [comment] 2020-10-28 12:46
If anyone is wanting to look at this, the idea is to raise `ConfigEntryNotReady` during the initialisation (inside `__init__.py > async_setup_entry`)
The issue will be to distinguish "internet errors" from "failed credentials" so might need some changes to PyZE library

**Comment by JeedHome44** [comment] 2020-11-20 14:15
Hello,

Is it possible to create a service that allows you to restart synchronization manually?
That would allow it to be automatically restarted in an automation as soon as my Zoe leaves or arrives from the house for example.
This would temporarily resolve this problem.

Thank you

**Comment by JeedHome44** [comment] 2020-11-26 12:40
can we use hassio.addon_restart with an automation?

if yes? how please?

**Comment by epenet** [comment] 2020-12-04 14:33
@JeedHome44 [release v3.0.2](https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2) has updated the startup routine, and implements ConfigEntryNotReady so HA should automatically re-attempt if the failure occurs at startup ?

If not, then please provide some **logs/traces/anything** that helps us understand what the issue is.

**Comment by JeedHome44** [comment] 2020-12-04 14:48
Oh thank you!
I will test that 😉

**Comment by JeedHome44** [comment] 2020-12-05 21:10
I downloaded the renault file.
I restarted Hassio but I cannot find "Renault" in the list of integrations.
Why?

**Comment by JeedHome44** [comment] 2020-12-05 21:14
Is there a minimum version of Home assistant to have?

**Comment by epenet** [comment] 2020-12-05 21:28
Tested again v118 - haven't tested against earlier versions

**Comment by JeedHome44** [comment] 2020-12-05 21:46
I have Home Assistant Core  0.105.3 and HassOS 5.2
I have to update to 0.118.5?

**Comment by JeedHome44** [comment] 2020-12-06 01:10
I do not understand.

I updated the Core. I was able to install the integration afterwards. It displayed the information well at the beginning and then it put this ...

Why?

**Comment by JeedHome44** [comment] 2020-12-06 01:10
![Capture2](https://user-images.githubusercontent.com/41892950/101268834-3cbbd000-3768-11eb-9fa2-0f08223c4498.JPG)
![Capture](https://user-images.githubusercontent.com/41892950/101268835-3f1e2a00-3768-11eb-86ea-d9e14538b076.JPG)

**Comment by JeedHome44** [comment] 2020-12-06 01:57
I hadn't disabled the sensor using PyZE and I think it was conflicting. It is working now.
But how do I adapt my scripts to activate the calendar, the preconditioning ... with this integration?
I had not yet updated 3.0

```
'1589190413353':
  alias: zoe40_ac_start_now_19
  sequence:
  - data:
      temperature: 19
    entity_id: sensor.zoe40
    service: renaultze.ac_start
'1589190456408':
  alias: zoe40_ac_cancel
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.ac_cancel
'1589190499937':
  alias: zoe40_charge_start
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.charge_start
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
'1589206784082':
  alias: zoe40_calendrier_off
  sequence:
  - data:
      charge_mode: always_charging
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
'1589232410704':
  alias: zoe40_ac_start_now_22
  sequence:
  - data:
      temperature: 22
    entity_id: sensor.zoe40
    service: renaultze.ac_start
'1589476771733':
  alias: zoe40_calendrier_refresh
  sequence:
  - data:
      schedules:
        activated: true
        friday:
          duration: 240
          startTime: T02:00Z
        id: 1
        monday:
          duration: 240
          startTime: T02:00Z
        saturday:
          duration: 240
          startTime: T02:00Z
        sunday:
          duration: 240
          startTime: T02:00Z
        thursday:
          duration: 240
          startTime: T02:00Z
        tuesday:
          duration: 240
          startTime: T02:00Z
        wednesday:
          duration: 240
          startTime: T02:00Z
    entity_id: sensor.zoe40
    service: renaultze.charge_set_schedules
```

**Comment by JeedHome44** [comment] 2020-12-06 02:06
For the calendar, is it possible to translate "SCHEDULE_MODE" by "Activated", "Activé" in french, and "ALWAYS_CHARGING" by "Deactivated", "Désactivé" in french?

![Capture](https://user-images.githubusercontent.com/41892950/101269529-fd917d00-376f-11eb-9921-9783fa57f9d4.JPG)

**Comment by JeedHome44** [comment] 2020-12-06 02:29
Je viens de tester en changeant les scripts de cette façon, mais ça ne marche pas...

```
'1589190413353':
  alias: zoe40_ac_start_now_19
  sequence:
  - data:
      temperature: 19
      vin: vf1XXXXXXXXX
    service: renault.ac_start
'1589190456408':
  alias: zoe40_ac_cancel
  sequence:
  - data:
      vin: vf1XXXXXXXXX
    service: renault.ac_cancel
'1589190499937':
  alias: zoe40_charge_start
  sequence:
  - data:
      vin: vf1XXXXXXXXX
    service: renault.charge_start
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
      vin: vf1XXXXXXXXX
    service: renault.charge_set_mode
'1589206784082':
  alias: zoe40_calendrier_off
  sequence:
  - data:
      charge_mode: always_charging
      vin: vf1XXXXXXXXX
    service: renault.charge_set_mode
'1589232410704':
  alias: zoe40_ac_start_now_22
  sequence:
  - data:
      temperature: 22
      vin: vf1XXXXXXXXX
    service: renault.ac_start
'1589476771733':
  alias: zoe40_calendrier_refresh
  sequence:
  - data:
      schedules:
        activated: true
        friday:
          duration: 240
          startTime: T02:00Z
        id: 1
        monday:
          duration: 240
          startTime: T02:00Z
        saturday:
          duration: 240
          startTime: T02:00Z
        sunday:
          duration: 240
          startTime: T02:00Z
        thursday:
          duration: 240
          startTime: T02:00Z
        tuesday:
          duration: 240
          startTime: T02:00Z
        wednesday:
          duration: 240
          startTime: T02:00Z
      vin: vf1XXXXXXXXX
    service: renault.charge_set_schedules
```

**Comment by epenet** [comment] 2020-12-06 10:11
Can you send traces of the errors ?
Without traces, it's impossible to help you.

**Comment by JeedHome44** [comment] 2020-12-06 10:43
how to get the logs? I have never done. thank you

**Comment by epenet** [comment] 2020-12-06 10:52
I don't know the specifics of HassOS, but generally on HA-Core you have to add this to YAML:

```
logger:
  default: error
  logs:
    renault_api: debug
    custom_components.renault: debug
```

**Comment by JeedHome44** [comment] 2020-12-06 12:44
when I run the script to put the calendar on always_charging for example, I have this message:

`Échec d'appel du service "script/1589190593760". value is not allowed for dictionary value @ data['charge_mode']`

if I want to start the preconditioning:

`Échec d'appel du service "script/1589190413353". Unable to find vehicle with VIN: vfXXXXXXXXX`

**Comment by JeedHome44** [comment] 2020-12-06 12:51
```
2020-12-06 13:43:20 ERROR (MainThread) [homeassistant.components.script.1589232410704] zoe40_ac_start_now_22: Error executing script. Unexpected error for call_service at pos 1: Unable to find vehicle with VIN: vfxxxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxxx
2020-12-06 13:43:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547843255168] Unable to find vehicle with VIN: vfxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxx
2020-12-06 13:43:54 ERROR (MainThread) [homeassistant.components.script.1589232410704] zoe40_ac_start_now_22: Error executing script. Unexpected error for call_service at pos 1: Unable to find vehicle with VIN: vf1xxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxx
2020-12-06 13:43:54 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547843255168] Unable to find vehicle with VIN: vfxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxx
2020-12-06 13:43:59 ERROR (MainThread) [homeassistant.components.script.1589190413353] zoe40_ac_start_now_19: Error executing script. Unexpected error for call_service at pos 1: Unable to find vehicle with VIN: vfxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vf1xxxxxxx
2020-12-06 13:43:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547843255168] Unable to find vehicle with VIN: vf1xxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxxx
2020-12-06 13:44:18 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 200 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/c0221f43-5622-4fac-ba1d-7b3051afc1a7/kamereon/kca/car-adapter/v2/cars/VFxxxxxxxx/cockpit?country=FR: {"data":{"type":"Car","id":"VF1xxxxxxxx","attributes":{"totalMileage":47390.07}}}
2020-12-06 13:44:18 DEBUG (MainThread) [custom_components.renault.renault_vehicle] Finished fetching VFxxxxxxxxx cockpit data in 1.278 seconds
2020-12-06 13:44:18 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 200 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxxxx/kamereon/kca/car-adapter/v1/cars/VFxxxxxxxxx/charge-mode?country=FR: {"data":{"type":"Car","id":"VFxxxxxxxxxxxx","attributes":{"chargeMode":"schedule_mode"}}}
2020-12-06 13:44:18 DEBUG (MainThread) [custom_components.renault.renault_vehicle] Finished fetching VFxxxxxxxx charge_mode data in 1.585 seconds
2020-12-06 13:44:19 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 200 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxx/kamereon/kca/car-adapter/v2/cars/VF1xxxxxxxxx/battery-status?country=FR: {"data":{"type":"Car","id":"VFxxxxxxxxx","attributes":{"timestamp":"2020-12-06T11:42:50+01:00","batteryLevel":88,"batteryTemperature":19,"batteryAutonomy":231,"batteryCapacity":0,"batteryAvailableEnergy":0,"plugStatus":0,"chargingStatus":-1.0}}}
2020-12-06 13:44:19 DEBUG (MainThread) [custom_components.renault.renault_vehicle] Finished fetching VFxxxxxxxx battery data in 2.295 seconds
2020-12-06 13:44:19 DEBUG (MainThread) [renault_api.kamereon] Received Kamereon response 200 on https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxx/kamereon/kca/car-adapter/v1/cars/VF1xxxxxxx/hvac-status?country=FR: {"data":{"type":"Car","id":"VFxxxxxxx","attributes":{"externalTemperature":12.0,"hvacStatus":"off"}}}
2020-12-06 13:44:19 DEBUG (MainThread) [custom_components.renault.renault_vehicle] Finished fetching VFxxxxxx hvac_status data in 2.351 seconds
```

**Comment by JeedHome44** [comment] 2020-12-06 12:55
```
2020-12-06 13:42:59 ERROR (MainThread) [homeassistant.components.script.1589190593760] zoe40_calendrier_on: Error executing script. Invalid data for call_service at pos 1: value is not allowed for dictionary value @ data['charge_mode']
2020-12-06 13:42:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547843255168] value is not allowed for dictionary value @ data['charge_mode']
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1405, in async_call
processed_data = handler.schema(service_data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value is not allowed for dictionary value @ data['charge_mode']
```

**Comment by JeedHome44** [comment] 2020-12-06 12:56
```
2020-12-06 13:41:45 ERROR (MainThread) [homeassistant.components.script.1589206784082] zoe40_calendrier_off: Error executing script. Invalid data for call_service at pos 1: value is not allowed for dictionary value @ data['charge_mode']
2020-12-06 13:41:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547843255168] value is not allowed for dictionary value @ data['charge_mode']
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 215, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 320, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1010, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 245, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1405, in async_call
processed_data = handler.schema(service_data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value is not allowed for dictionary value @ data['charge_mode']
```

**Comment by JeedHome44** [comment] 2020-12-06 12:58
```
2020-12-06 13:43:59 ERROR (MainThread) [homeassistant.components.script.1589190413353] zoe40_ac_start_now_19: Error executing script. Unexpected error for call_service at pos 1: Unable to find vehicle with VIN: vfxxxxxxx
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 253, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1451, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1486, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/renault/services.py", line 77, in ac_start
vehicle = get_vehicle(service_call_data)
File "/config/custom_components/renault/services.py", line 149, in get_vehicle
raise ValueError(f"Unable to find vehicle with VIN: {vin}")
ValueError: Unable to find vehicle with VIN: vfxxxxxxxx
```

**Comment by JeedHome44** [comment] 2020-12-06 12:59
I would point out that everything worked fine with version 2 for actions ;)

**Comment by epenet** [comment] 2020-12-06 13:17
Try capital letters on the VIN. 
I will check the rest tomorrow

**Comment by JeedHome44** [comment] 2020-12-06 13:32
thanks for this idea! It works! So I put the VIN in uppercase on all scripts. They all worked except charge_mode
So I tried to capitalize the words SCHEDULE_MODE and ALWAYS_CHARGING as well and it works. So everything must be capitalized. So you have to change that in the guide ;)

**Comment by JeedHome44** [comment] 2020-12-06 13:47
on the other hand, the function to deactivate the calendar works well. it passes it on ALWAYS_CHARGING. But I try with Charge mode or Calendar to turn it on and it doesn't seem to work. Before, there was only the calendar that worked to activate it but it does not seem to work ...

**Comment by JeedHome44** [comment] 2020-12-06 14:03
i opened an new issue.

**Comment by JeedHome44** [comment] 2020-12-08 09:40
I think, i have the problem now.

![Capture](https://user-images.githubusercontent.com/41892950/101466783-d094c400-3941-11eb-9dd0-d22de1846904.JPG)

**Comment by epenet** [comment] 2020-12-08 09:46
Do you have traces? Still can't help without traces...

**Comment by JeedHome44** [comment] 2020-12-08 09:51
in fact, I changed the weather this morning as mentioned in the other topic. instead of 5 minutes, I put 2.
I put back on 5 minutes but it does not seem to want to come back.
I only modified this line 14 renault_vehicule.py

`DEFAULT_SCAN_INTERVAL = timedelta(minutes=2)`

and i have this in the log:

`Error fetching VF1XXXXXXXXXX location data: Error communicating with API: ('err.func.wired.overloaded', 'You have reached your quota limit')`

**Comment by JeedHome44** [comment] 2020-12-08 09:53
how long do i have to wait for the renault server to accept my connection again?

**Comment by epenet** [comment] 2020-12-08 09:54
It shouldn't take too long - maybe 10-30 minutes

**Comment by JeedHome44** [comment] 2020-12-08 09:56
ok, so it is not possible to have a status feedback of less than 5 minutes. or maybe some other way but I don't know. maybe that was the problem I had in 2.0
ok, i'll notice the other ticket

**Comment by JeedHome44** [comment] 2020-12-08 10:00
I just got all the information :)

**Closed** 2020-12-10 08:37 UTC
Labels: enhancement, help wanted
